[project]
name = "helloagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hello-agents>=0.2.8",
    "openai>=1.109.1",
    "python-dotenv>=1.2.1",
]
